name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 14:40 运行一次, 中国时间 22:40
    - cron: '50 15 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZWNlZTZlYzA0ODU0ODUwYTQ2NjA4MTY5NDkyYTYxOSIsImF1ZCI6Ijc2OTE3Y2NjY2Q0NDQxYzM5NDU3YTA0ZjYwODRmYjJmIiwiZXhwIjoxNjg3NTA4Mjk4LCJpYXQiOjE2Nzk3MzIyOTh9.BaCUIKsE2H_VFJ_xELTaBKRh-G48kniN5_vGeDVHfT59DcitgCQdNrRGlJKtd7oofN-qwj4IXX-JyUV8p-Ue4A,eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzM2E3NmQxODIzNTI0NWIxYmY1YzRjY2I3MDU1NDU0YSIsImF1ZCI6Ijc2OTE3Y2NjY2Q0NDQxYzM5NDU3YTA0ZjYwODRmYjJmIiwiZXhwIjoxNjg3NTA4NDI5LCJpYXQiOjE2Nzk3MzI0Mjl9.I7CajfPVHGrTidwdv735gbGAa2jZ3Iyu9kwTuvGYWu35Zi4Qwvg-GQOhbQTLjTUmGUfGuPRmUysNfxxG_MLPgw}}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'PUSHPLUS'
          SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_TLS: ${{ secrets.SMTP_TLS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
          SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
